- removed include/ from the build - fixed the dumb (C) EVERYONE IN THE WORLD header to one more sensible. - cleaned various references claiming this was ircd-hybrid, its not.
git-svn-id: http://svn.ratbox.org/svnroot/trunk@13036 b93f080a-4cfa-0310-a19a-80a68f531ef9

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2316,7 +2316,7 @@ if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
   :
 else
   echo "$ac_t""no" 1>&6
-{ echo "configure: error: ** stdarg.h could not be found - ircd-hybrid will not compile without it **" 1>&2; exit 1; }
+{ echo "configure: error: ** stdarg.h could not be found - ircd-ratbox will not compile without it **" 1>&2; exit 1; }
 fi
 
 
