- added in the autoconf bollocks to deal with building sqlite.
git-svn-id: http://svn.ratbox.org/svnroot/trunk@20290 b93f080a-4cfa-0310-a19a-80a68f531ef9

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1995,6 +1995,11 @@ else
 	echo "$ac_t""no" 1>&6
 fi
 
+ac_cv_found_sqlite_inc="no"
+ac_cv_found_sqlite_lib="no"
+
+SQLITE_LIB="-lsqlite"
+
 SQLITE_INCLUDES=""
 # Check whether --with-sqlite or --without-sqlite was given.
 if test "${with_sqlite+set}" = set; then
@@ -2007,17 +2012,17 @@ fi
 
 ac_safe=`echo "sqlite.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for sqlite.h""... $ac_c" 1>&6
-echo "configure:2011: checking for sqlite.h" >&5
+echo "configure:2016: checking for sqlite.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2016 "configure"
+#line 2021 "configure"
 #include "confdefs.h"
 #include <sqlite.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:2021: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:2026: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -2033,26 +2038,27 @@ rm -f conftest*
 fi
 if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
   echo "$ac_t""yes" 1>&6
-  :
+  
+	ac_cv_found_sqlite_inc="yes"
+
 else
   echo "$ac_t""no" 1>&6
 
 	echo $ac_n "checking for sqlite.h in given path""... $ac_c" 1>&6
-echo "configure:2042: checking for sqlite.h in given path" >&5
+echo "configure:2049: checking for sqlite.h in given path" >&5
 	if test -f "$SQLITE_DIR/include/sqlite.h"; then
 		SQLITE_INCLUDES="-I $SQLITE_DIR/include/"
 		echo "$ac_t""yes" 1>&6
+		ac_cv_found_sqlite_inc="yes"
 	else
 		echo "$ac_t""no" 1>&6
-		echo "Cannot find SQLite headers.  Please specify search path --with-sqlite=DIR"
-		exit
 	fi
 
 fi
 
 
 echo $ac_n "checking for main in -lsqlite""... $ac_c" 1>&6
-echo "configure:2056: checking for main in -lsqlite" >&5
+echo "configure:2062: checking for main in -lsqlite" >&5
 ac_lib_var=`echo sqlite'_'main | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -2060,14 +2066,14 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lsqlite  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 2064 "configure"
+#line 2070 "configure"
 #include "confdefs.h"
 
 int main() {
 main()
 ; return 0; }
 EOF
-if { (eval echo configure:2071: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:2077: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -2082,32 +2088,42 @@ LIBS="$ac_save_LIBS"
 fi
 if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
   echo "$ac_t""yes" 1>&6
-    ac_tr_lib=HAVE_LIB`echo sqlite | sed -e 's/[^a-zA-Z0-9_]/_/g' \
-    -e 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/'`
-  cat >> confdefs.h <<EOF
-#define $ac_tr_lib 1
-EOF
-
-  LIBS="-lsqlite $LIBS"
+  
+	ac_cv_found_sqlite_lib="yes"
 
 else
   echo "$ac_t""no" 1>&6
 
 	echo $ac_n "checking for main in -lsqlite in given path""... $ac_c" 1>&6
-echo "configure:2098: checking for main in -lsqlite in given path" >&5
+echo "configure:2099: checking for main in -lsqlite in given path" >&5
 
 	if test -e "$SQLITE_DIR/lib/libsqlite.so"; then
 		LDFLAGS="$LDFLAGS -L$SQLITE_DIR/lib/"
 		LIBS="$LIBS -lsqlite"
 		echo "$ac_t""yes" 1>&6
+		ac_cv_found_sqlite_lib="yes"
 	else
 		echo "$ac_t""no" 1>&6
-		echo "Cannot find SQLite library libsqlite.so.  Please specify search path --with-sqlite=DIR"
-		exit
 	fi
 
 fi
 
+
+echo $ac_n "checking sqlite was found""... $ac_c" 1>&6
+echo "configure:2114: checking sqlite was found" >&5
+
+if test "X$ac_cv_found_sqlite_inc" != "Xyes" || test "X$ac_cv_found_sqlite_lib" != "Xyes"; then
+	subdirs="sqlite"
+
+	echo "$ac_t""no" 1>&6
+	SQLITE_INCLUDES="-I ../sqlite/"
+	SQLITE_SUBDIR="sqlite"
+	SQLITE_LIB="../sqlite/.libs/libsqlite.a"
+else
+	echo "$ac_t""yes" 1>&6
+	SQLITE_SUBDIR=""
+		no_recursion="yes"
+fi
 
 # Check whether --with-nicklen or --without-nicklen was given.
 if test "${with_nicklen+set}" = set; then
@@ -2139,7 +2155,9 @@ cat >> confdefs.h <<EOF
 EOF
 
 
- 
+
+
+
 
 
 
@@ -2302,7 +2320,10 @@ s%@CP@%$CP%g
 s%@MV@%$MV%g
 s%@AR@%$AR%g
 s%@CPP@%$CPP%g
+s%@subdirs@%$subdirs%g
 s%@SQLITE_INCLUDES@%$SQLITE_INCLUDES%g
+s%@SQLITE_SUBDIR@%$SQLITE_SUBDIR%g
+s%@SQLITE_LIB@%$SQLITE_LIB%g
 s%@S_NICKSERV@%$S_NICKSERV%g
 s%@S_CHANSERV@%$S_CHANSERV%g
 s%@S_USERSERV@%$S_USERSERV%g
@@ -2533,6 +2554,103 @@ EOF
 chmod +x $CONFIG_STATUS
 rm -fr confdefs* $ac_clean_files
 test "$no_create" = yes || ${CONFIG_SHELL-/bin/sh} $CONFIG_STATUS || exit 1
+
+if test "$no_recursion" != yes; then
+
+  # Remove --cache-file and --srcdir arguments so they do not pile up.
+  ac_sub_configure_args=
+  ac_prev=
+  for ac_arg in $ac_configure_args; do
+    if test -n "$ac_prev"; then
+      ac_prev=
+      continue
+    fi
+    case "$ac_arg" in
+    -cache-file | --cache-file | --cache-fil | --cache-fi \
+    | --cache-f | --cache- | --cache | --cach | --cac | --ca | --c)
+      ac_prev=cache_file ;;
+    -cache-file=* | --cache-file=* | --cache-fil=* | --cache-fi=* \
+    | --cache-f=* | --cache-=* | --cache=* | --cach=* | --cac=* | --ca=* | --c=*)
+      ;;
+    -srcdir | --srcdir | --srcdi | --srcd | --src | --sr)
+      ac_prev=srcdir ;;
+    -srcdir=* | --srcdir=* | --srcdi=* | --srcd=* | --src=* | --sr=*)
+      ;;
+    *) ac_sub_configure_args="$ac_sub_configure_args $ac_arg" ;;
+    esac
+  done
+
+  for ac_config_dir in sqlite; do
+
+    # Do not complain, so a configure script can configure whichever
+    # parts of a large source tree are present.
+    if test ! -d $srcdir/$ac_config_dir; then
+      continue
+    fi
+
+    echo configuring in $ac_config_dir
+
+    case "$srcdir" in
+    .) ;;
+    *)
+      if test -d ./$ac_config_dir || mkdir ./$ac_config_dir; then :;
+      else
+        { echo "configure: error: can not create `pwd`/$ac_config_dir" 1>&2; exit 1; }
+      fi
+      ;;
+    esac
+
+    ac_popdir=`pwd`
+    cd $ac_config_dir
+
+      # A "../" for each directory in /$ac_config_dir.
+      ac_dots=`echo $ac_config_dir|sed -e 's%^\./%%' -e 's%[^/]$%&/%' -e 's%[^/]*/%../%g'`
+
+    case "$srcdir" in
+    .) # No --srcdir option.  We are building in place.
+      ac_sub_srcdir=$srcdir ;;
+    /*) # Absolute path.
+      ac_sub_srcdir=$srcdir/$ac_config_dir ;;
+    *) # Relative path.
+      ac_sub_srcdir=$ac_dots$srcdir/$ac_config_dir ;;
+    esac
+
+    # Check for guested configure; otherwise get Cygnus style configure.
+    if test -f $ac_sub_srcdir/configure; then
+      ac_sub_configure=$ac_sub_srcdir/configure
+    elif test -f $ac_sub_srcdir/configure.in; then
+      ac_sub_configure=$ac_configure
+    else
+      echo "configure: warning: no configuration information is in $ac_config_dir" 1>&2
+      ac_sub_configure=
+    fi
+
+    # The recursion is here.
+    if test -n "$ac_sub_configure"; then
+
+      # Make the cache file name correct relative to the subdirectory.
+      case "$cache_file" in
+      /*) ac_sub_cache_file=$cache_file ;;
+      *) # Relative path.
+        ac_sub_cache_file="$ac_dots$cache_file" ;;
+      esac
+  case "$ac_given_INSTALL" in
+        [/$]*) INSTALL="$ac_given_INSTALL" ;;
+        *) INSTALL="$ac_dots$ac_given_INSTALL" ;;
+        esac
+
+      echo "running ${CONFIG_SHELL-/bin/sh} $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir"
+      # The eval makes quoting arguments work.
+      if eval ${CONFIG_SHELL-/bin/sh} $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir
+      then :
+      else
+        { echo "configure: error: $ac_sub_configure failed for $ac_config_dir" 1>&2; exit 1; }
+      fi
+    fi
+
+    cd "$ac_popdir"
+  done
+fi
 
 
 echo
