modified ircd-hybrid-7/autoconf/configure.in to check properly for sys/event.h if kqueue is selected and to properly discard prepend underscore checking in shared libraries when nlist.h cannot be found updated configure from autoconf/configure.in
git-svn-id: http://svn.ratbox.org/svnroot/trunk@7825 b93f080a-4cfa-0310-a19a-80a68f531ef9

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3041,41 +3041,81 @@ fi
 
 
 if test "$ac_cv_func_kqueue" = "yes" ; then
-        SELECT_TYPE="kqueue"   
-	cat >> confdefs.h <<\EOF
+	ac_safe=`echo "sys/event.h" | sed 'y%./+-%__p_%'`
+echo $ac_n "checking for sys/event.h""... $ac_c" 1>&6
+echo "configure:3047: checking for sys/event.h" >&5
+if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  cat > conftest.$ac_ext <<EOF
+#line 3052 "configure"
+#include "confdefs.h"
+#include <sys/event.h>
+EOF
+ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
+{ (eval echo configure:3057: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
+if test -z "$ac_err"; then
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=yes"
+else
+  echo "$ac_err" >&5
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=no"
+fi
+rm -f conftest*
+fi
+if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+   event_h="sys/event.h" 
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+	if test "X$event_h" = "X" ; then
+		echo "configure: warning: ** sys/event.h not found - can not build kqueue support without it **" 1>&2
+	else
+	        SELECT_TYPE="kqueue"
+		cat >> confdefs.h <<\EOF
 #define USE_KQUEUE 1
 EOF
 
-elif test "$ac_cv_func_devpoll" = "yes" ; then
-        SELECT_TYPE="devpoll"
-        cat >> confdefs.h <<\EOF
+	fi
+fi
+if test "$SELECT_TYPE" != "kqueue" ; then
+	if test "$ac_cv_func_devpoll" = "yes" ; then
+        	SELECT_TYPE="devpoll"
+        	cat >> confdefs.h <<\EOF
 #define HAVE_DEVPOLL 1
 EOF
 
-	cat >> confdefs.h <<\EOF
+		cat >> confdefs.h <<\EOF
 #define USE_DEVPOLL 1
 EOF
 
-elif test "$ac_cv_func_poll" = "yes" ; then
-        SELECT_TYPE="poll"
-	cat >> confdefs.h <<\EOF
+	elif test "$ac_cv_func_poll" = "yes" ; then
+	        SELECT_TYPE="poll"
+		cat >> confdefs.h <<\EOF
 #define USE_POLL 1
 EOF
 
-elif test "$ac_cv_func_select" = "yes" ; then
-        SELECT_TYPE="select"
-	cat >> confdefs.h <<\EOF
+	elif test "$ac_cv_func_select" = "yes" ; then
+	        SELECT_TYPE="select"
+		cat >> confdefs.h <<\EOF
 #define USE_SELECT 1
 EOF
 
-else
-        echo "Eep!  Can't find kqueue, devpoll, poll _or_ select!"
-        echo "I'll try select and hope for the best."
-        SELECT_TYPE="select"
-	cat >> confdefs.h <<\EOF
+	else
+	        echo "Eep!  Can't find kqueue, devpoll, poll _or_ select!"
+	        echo "I'll try select and hope for the best."
+	        SELECT_TYPE="select"
+		cat >> confdefs.h <<\EOF
 #define USE_SELECT 1
 EOF
 
+	fi
 fi
 echo "Using ${SELECT_TYPE} for select loop."
 cat >> confdefs.h <<EOF
@@ -3144,12 +3184,12 @@ else
 	MOD_TARGET="shared_modules"
 	
 	echo $ac_n "checking for dlopen""... $ac_c" 1>&6
-echo "configure:3148: checking for dlopen" >&5
+echo "configure:3188: checking for dlopen" >&5
 if eval "test \"`echo '$''{'ac_cv_func_dlopen'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 3153 "configure"
+#line 3193 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char dlopen(); below.  */
@@ -3172,7 +3212,7 @@ dlopen();
 
 ; return 0; }
 EOF
-if { (eval echo configure:3176: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:3216: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_dlopen=yes"
 else
@@ -3190,7 +3230,7 @@ if eval "test \"`echo '$ac_cv_func_'dlopen`\" = yes"; then
 else
   echo "$ac_t""no" 1>&6
 echo $ac_n "checking for dlopen in -ldl""... $ac_c" 1>&6
-echo "configure:3194: checking for dlopen in -ldl" >&5
+echo "configure:3234: checking for dlopen in -ldl" >&5
 ac_lib_var=`echo dl'_'dlopen | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -3198,7 +3238,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-ldl  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 3202 "configure"
+#line 3242 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -3209,7 +3249,7 @@ int main() {
 dlopen()
 ; return 0; }
 EOF
-if { (eval echo configure:3213: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:3253: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -3245,17 +3285,17 @@ fi
 	# all symbols visible in the dynamic symbol table.
 	hold_ldflags=$LDFLAGS
 	echo $ac_n "checking for the ld -export-dynamic flag""... $ac_c" 1>&6
-echo "configure:3249: checking for the ld -export-dynamic flag" >&5
+echo "configure:3289: checking for the ld -export-dynamic flag" >&5
 	LDFLAGS="${LDFLAGS} -Wl,-export-dynamic"
 	cat > conftest.$ac_ext <<EOF
-#line 3252 "configure"
+#line 3292 "configure"
 #include "confdefs.h"
 
 int main() {
 int i;
 ; return 0; }
 EOF
-if { (eval echo configure:3259: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:3299: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   found=yes
 else
@@ -3272,7 +3312,7 @@ rm -f conftest*
 	fi
 
 	echo $ac_n "checking for compiler option to produce PIC""... $ac_c" 1>&6
-echo "configure:3276: checking for compiler option to produce PIC" >&5
+echo "configure:3316: checking for compiler option to produce PIC" >&5
 	if test "$ac_cv_prog_gcc" = "yes"; then
 		echo "$ac_t""gcc: -fPIC -DPIC -shared" 1>&6
 		PICFLAGS="-fPIC -DPIC -shared"
@@ -3292,12 +3332,12 @@ echo "configure:3276: checking for compiler option to produce PIC" >&5
 
 	nlist_lib=""
 	echo $ac_n "checking for nlist""... $ac_c" 1>&6
-echo "configure:3296: checking for nlist" >&5
+echo "configure:3336: checking for nlist" >&5
 if eval "test \"`echo '$''{'ac_cv_func_nlist'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 3301 "configure"
+#line 3341 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char nlist(); below.  */
@@ -3320,7 +3360,7 @@ nlist();
 
 ; return 0; }
 EOF
-if { (eval echo configure:3324: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:3364: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_nlist=yes"
 else
@@ -3338,7 +3378,7 @@ if eval "test \"`echo '$ac_cv_func_'nlist`\" = yes"; then
 else
   echo "$ac_t""no" 1>&6
 echo $ac_n "checking for nlist in -ldl""... $ac_c" 1>&6
-echo "configure:3342: checking for nlist in -ldl" >&5
+echo "configure:3382: checking for nlist in -ldl" >&5
 ac_lib_var=`echo dl'_'nlist | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -3346,7 +3386,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-ldl  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 3350 "configure"
+#line 3390 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -3357,7 +3397,7 @@ int main() {
 nlist()
 ; return 0; }
 EOF
-if { (eval echo configure:3361: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:3401: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -3376,7 +3416,7 @@ if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
 else
   echo "$ac_t""no" 1>&6
 echo $ac_n "checking for nlist in -lelf""... $ac_c" 1>&6
-echo "configure:3380: checking for nlist in -lelf" >&5
+echo "configure:3420: checking for nlist in -lelf" >&5
 ac_lib_var=`echo elf'_'nlist | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -3384,7 +3424,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lelf  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 3388 "configure"
+#line 3428 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -3395,7 +3435,7 @@ int main() {
 nlist()
 ; return 0; }
 EOF
-if { (eval echo configure:3399: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:3439: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -3425,17 +3465,17 @@ fi
 
 			ac_safe=`echo "libelf/nlist.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for libelf/nlist.h""... $ac_c" 1>&6
-echo "configure:3429: checking for libelf/nlist.h" >&5
+echo "configure:3469: checking for libelf/nlist.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 3434 "configure"
+#line 3474 "configure"
 #include "confdefs.h"
 #include <libelf/nlist.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:3439: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:3479: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -3458,17 +3498,17 @@ fi
 
 	ac_safe=`echo "elf/nlist.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for elf/nlist.h""... $ac_c" 1>&6
-echo "configure:3462: checking for elf/nlist.h" >&5
+echo "configure:3502: checking for elf/nlist.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 3467 "configure"
+#line 3507 "configure"
 #include "confdefs.h"
 #include <elf/nlist.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:3472: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:3512: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -3491,17 +3531,17 @@ fi
 
 	ac_safe=`echo "nlist.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for nlist.h""... $ac_c" 1>&6
-echo "configure:3495: checking for nlist.h" >&5
+echo "configure:3535: checking for nlist.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 3500 "configure"
+#line 3540 "configure"
 #include "confdefs.h"
 #include <nlist.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:3505: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:3545: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -3517,24 +3557,30 @@ rm -f conftest*
 fi
 if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
   echo "$ac_t""yes" 1>&6
-   nlist_h="nlist.h"  
+   nlist_h="nlist.h" 
 else
   echo "$ac_t""no" 1>&6
 fi
 
 	if test x"$nlist_h" = "x"; then
 		echo "configure: warning: ** cannot locate an nlist.h **" 1>&2
-	fi
-	echo $ac_n "checking for extra underscores prepended to symbol names""... $ac_c" 1>&6
-echo "configure:3530: checking for extra underscores prepended to symbol names" >&5
-	if eval "test \"`echo '$''{'symbol_underscores'+set}'`\" = set"; then
+		echo "configure: warning: ** cannot check for extra underscores prepended to symbol names - nlist.h is missing **" 1>&2
+		echo "configure: warning: ** assuming no underscores prepend symbol names **" 1>&2
+		cat >> confdefs.h <<EOF
+#define SYMBOL_PREFIX ""
+EOF
+
+	else
+		echo $ac_n "checking for extra underscores prepended to symbol names""... $ac_c" 1>&6
+echo "configure:3576: checking for extra underscores prepended to symbol names" >&5
+		if eval "test \"`echo '$''{'symbol_underscores'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   
 cat << EOF > conftest.c
 	#include <$nlist_h>
 	#include <stdio.h>
-  #include <stdlib.h>
+	#include <stdlib.h>
 	void _modinit(void);
 	int main(int argc, char *argv[]) {
         	int i;
@@ -3574,13 +3620,14 @@ EOF
 		symbol_underscores=`./conftest conftest`
 		echo "$ac_t""$symbol_underscores" 1>&6
 		$RM -f conftest conftest.c
-	
+		
 fi
 
-	cat >> confdefs.h <<EOF
+		cat >> confdefs.h <<EOF
 #define SYMBOL_PREFIX "${symbol_underscores}"
 EOF
 
+	fi
 fi 
 
   
