- add a check for us not finding any suitable io interfaces
git-svn-id: http://svn.ratbox.org/svnroot/trunk@15696 b93f080a-4cfa-0310-a19a-80a68f531ef9

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8581,6 +8581,12 @@ fi
 
 fi
 
+if test -z "$SELECT_TYPE"; then
+	{ { echo "$as_me:$LINENO: error: Unable to find a usable IO interface" >&5
+echo "$as_me: error: Unable to find a usable IO interface" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 echo "Using $SELECT_TYPE for select loop."
 
 
